"""Integration tests of the STEP import through OpenCASCADE.

They require `uv sync --extra cad`. Run with: ``uv run pytest -m cad``

The fixture `tests/data/fixture.step` is generated by `tools/make_step_fixture.py`
and is versioned — it is small (50 kB) and the tests need it. Real CAD files are not
in the repository.

The assembly in the fixture:

    base                     assembly, the root
      portal                 assembly, +100 mm in X
        Part1                two siblings of the same name
        Part1
        head                 rotated by 90° about Z
      cover                  the only part with a colour (0.2, 0.4, 0.8)
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest

from pssim.cad.cache import CacheEntry
from pssim.cad.mesh import read_mesh
from pssim.cad.model import DEFAULT_COLOR, CadAssembly
from pssim.cad.step_import import (
    ImportSettings,
    build_paths,
    cache_key_for,
    import_step,
    read_step_assembly,
)
from pssim.domain.errors import CadImportError

pytestmark = pytest.mark.cad

FIXTURE = Path(__file__).resolve().parents[1] / "data" / "fixture.step"

#: Values from tools/make_step_fixture.py, converted into metres.
PORTAL_OFFSET_M = 0.1
PART_SPACING_M = 0.04
COVER_OFFSET_M = -0.04
COVER_COLOR = (0.2, 0.4, 0.8, 1.0)
BOX_TRIANGLES = 12
"""A box = 6 faces × 2 triangles."""


def settings(scale_to_m: float = 1e-3, units: str = "mm") -> ImportSettings:
    return ImportSettings(step_file=FIXTURE, scale_to_m=scale_to_m, units=units)


@pytest.fixture(scope="module")
def assembly() -> CadAssembly:
    """The imported fixture. Module scope — the import takes seconds."""
    return build_paths(read_step_assembly(settings()))


class TestAssemblyTree:
    def test_fixture_existuje(self) -> None:
        # Without it there is no point running the rest — generate it with make_step_fixture.py.
        assert FIXTURE.is_file(), f"{FIXTURE} is missing; run tools/make_step_fixture.py"

    def test_the_assembly_has_a_single_root(self, assembly: CadAssembly) -> None:
        assert assembly.roots == ("base",)

    def test_the_hierarchy_is_preserved(self, assembly: CadAssembly) -> None:
        assert {node.path for node in assembly.nodes} == {
            "base",
            "base/portal",
            "base/portal/Part1[1]",
            "base/portal/Part1[2]",
            "base/portal/head",
            "base/cover",
        }

    def test_part_names_survive_the_round_trip(self, assembly: CadAssembly) -> None:
        # STEP names sit on the definition, not on the instance — read them wrongly
        # and everything comes back as Unnamed_*.
        assert not any(node.name.startswith("Unnamed") for node in assembly.nodes)

    def test_children_are_recorded_on_the_parent(self, assembly: CadAssembly) -> None:
        portal = assembly.node("base/portal")

        assert portal is not None
        assert set(portal.children) == {
            "base/portal/Part1[1]",
            "base/portal/Part1[2]",
            "base/portal/head",
        }


class TestDuplicateNames:
    def test_siblings_of_the_same_name_get_an_index(self, assembly: CadAssembly) -> None:
        # The same part used twice = one definition, two instances.
        paths = {node.path for node in assembly.nodes}

        assert {"base/portal/Part1[1]", "base/portal/Part1[2]"} <= paths

    def test_a_unique_name_gets_no_index(self, assembly: CadAssembly) -> None:
        assert assembly.node("base/portal/head") is not None

    def test_instances_have_different_positions(self, assembly: CadAssembly) -> None:
        first = assembly.node("base/portal/Part1[1]")
        second = assembly.node("base/portal/Part1[2]")

        assert first is not None
        assert second is not None
        assert second.transform.xyz[1] - first.transform.xyz[1] == pytest.approx(
            PART_SPACING_M, abs=1e-9
        )


class TestUnits:
    def test_translation_converts_from_mm_to_metres(self, assembly: CadAssembly) -> None:
        # In the fixture the portal is offset by 100 mm.
        portal = assembly.node("base/portal")

        assert portal is not None
        assert portal.transform.xyz[0] == pytest.approx(PORTAL_OFFSET_M, abs=1e-9)

    def test_a_negative_offset_keeps_its_sign(self, assembly: CadAssembly) -> None:
        cover = assembly.node("base/cover")

        assert cover is not None
        assert cover.transform.xyz[1] == pytest.approx(COVER_OFFSET_M, abs=1e-9)

    def test_without_scaling_it_stays_in_millimetres(self) -> None:
        # A control sample: if the scaling did nothing, the previous tests would pass
        # anyway. This one shows it is really applied.
        raw = build_paths(read_step_assembly(settings(scale_to_m=1.0, units="m")))
        portal = raw.node("base/portal")

        assert portal is not None
        assert portal.transform.xyz[0] == pytest.approx(100.0, abs=1e-6)


class TestRotation:
    def test_a_rotated_part_has_a_rotation_about_z(self, assembly: CadAssembly) -> None:
        head = assembly.node("base/portal/head")

        assert head is not None
        assert head.transform.rpy[2] == pytest.approx(math.pi / 2, abs=1e-9)

    def test_an_unrotated_part_has_no_rotation(self, assembly: CadAssembly) -> None:
        portal = assembly.node("base/portal")

        assert portal is not None
        assert portal.transform.rpy == pytest.approx((0.0, 0.0, 0.0), abs=1e-9)

    def test_rotation_is_not_scaled_by_units(self) -> None:
        # Angles are dimensionless — scaling a length must not touch them.
        raw = build_paths(read_step_assembly(settings(scale_to_m=1.0, units="m")))
        head = raw.node("base/portal/head")

        assert head is not None
        assert head.transform.rpy[2] == pytest.approx(math.pi / 2, abs=1e-9)


class TestColours:
    def test_a_part_with_a_colour_keeps_it(self, assembly: CadAssembly) -> None:
        cover = assembly.node("base/cover")

        assert cover is not None
        assert cover.color == pytest.approx(COVER_COLOR, abs=1e-6)

    def test_a_part_without_a_colour_gets_the_default(self, assembly: CadAssembly) -> None:
        # A part without a colour is entirely common in real files.
        head = assembly.node("base/portal/head")

        assert head is not None
        assert head.color == pytest.approx(DEFAULT_COLOR, abs=1e-6)


class TestGeometry:
    def test_the_parts_are_tessellated(self, assembly: CadAssembly) -> None:
        head = assembly.node("base/portal/head")

        assert head is not None
        assert head.triangle_count == BOX_TRIANGLES

    def test_an_assembly_node_has_no_geometry_of_its_own(self, assembly: CadAssembly) -> None:
        portal = assembly.node("base/portal")

        assert portal is not None
        assert portal.has_geometry is False

    def test_celkovy_pocet_trojuholnikov(self, assembly: CadAssembly) -> None:
        # Four boxes × 12 triangles.
        assert assembly.triangle_count == 4 * BOX_TRIANGLES

    def test_jemnejsia_deflection_nezhorsi_geometriu(self) -> None:
        fine = ImportSettings(
            step_file=FIXTURE, scale_to_m=1e-3, units="mm", linear_deflection_mm=0.01
        )
        result = build_paths(read_step_assembly(fine))

        assert result.triangle_count >= 4 * BOX_TRIANGLES


class TestWritingGeometry:
    def test_the_import_writes_mesh_files(self, tmp_path: Path) -> None:
        import_step(settings(), tmp_path)

        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))
        meshes = list(entry.directory.glob("*.npz"))

        # Three part definitions: Part1, head, cover. Not four — the two Part1
        # instances share one file.
        assert len(meshes) == 3

    def test_instances_of_one_part_point_at_one_file(self, tmp_path: Path) -> None:
        metadata = import_step(settings(), tmp_path)

        first = metadata.assembly.node("base/portal/Part1[1]")
        second = metadata.assembly.node("base/portal/Part1[2]")

        assert first is not None
        assert second is not None
        assert first.mesh == second.mesh

    def test_the_mesh_can_be_read_back(self, tmp_path: Path) -> None:
        metadata = import_step(settings(), tmp_path)
        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))
        cover = metadata.assembly.node("base/cover")

        assert cover is not None
        assert cover.mesh is not None
        mesh = read_mesh(entry.mesh_path(cover.mesh))

        assert mesh.triangle_count == BOX_TRIANGLES

    def test_the_mesh_dimensions_are_in_metres(self, tmp_path: Path) -> None:
        # Kryt je vo fixture 200 x 5 x 80 mm.
        metadata = import_step(settings(), tmp_path)
        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))
        cover = metadata.assembly.node("base/cover")

        assert cover is not None
        assert cover.mesh is not None
        low, high = read_mesh(entry.mesh_path(cover.mesh)).bounding_box()

        assert high[0] - low[0] == pytest.approx(0.2, abs=1e-6)
        assert high[1] - low[1] == pytest.approx(0.005, abs=1e-6)
        assert high[2] - low[2] == pytest.approx(0.08, abs=1e-6)

    def test_kvader_ma_ocakavany_pocet_vrcholov(self, tmp_path: Path) -> None:
        # 6 faces × 4 vertices, not shared between faces — otherwise the normals on
        # the edges would be averaged and the box would look rounded.
        metadata = import_step(settings(), tmp_path)
        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))
        head = metadata.assembly.node("base/portal/head")

        assert head is not None
        assert head.mesh is not None
        assert read_mesh(entry.mesh_path(head.mesh)).vertex_count == 24

    def test_the_normals_are_unit_length(self, tmp_path: Path) -> None:
        metadata = import_step(settings(), tmp_path)
        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))
        head = metadata.assembly.node("base/portal/head")

        assert head is not None
        assert head.mesh is not None
        mesh = read_mesh(entry.mesh_path(head.mesh))

        lengths = np.linalg.norm(mesh.normals, axis=1)

        assert lengths == pytest.approx(np.ones(mesh.vertex_count), abs=1e-5)

    def test_normaly_kvadra_mieria_von(self, tmp_path: Path) -> None:
        # If the winding were corrected wrongly, the normals would point inwards and
        # the part would look inside out in the scene.
        metadata = import_step(settings(), tmp_path)
        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))
        head = metadata.assembly.node("base/portal/head")

        assert head is not None
        assert head.mesh is not None
        mesh = read_mesh(entry.mesh_path(head.mesh))

        low, high = mesh.bounding_box()
        center = np.array([(low[i] + high[i]) / 2 for i in range(3)])
        outward = mesh.vertices - center
        # The dot product of the normal with the outward direction must be positive.
        alignment = np.einsum("ij,ij->i", outward, mesh.normals)

        assert (alignment > 0).all()

    def test_an_empty_mesh_is_not_written(self, tmp_path: Path) -> None:
        import_step(settings(), tmp_path)
        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))

        for mesh_file in entry.directory.glob("*.npz"):
            assert read_mesh(mesh_file).triangle_count > 0


class TestCache:
    def test_the_import_writes_the_cache(self, tmp_path: Path) -> None:
        metadata = import_step(settings(), tmp_path)

        entry = CacheEntry(root=tmp_path, key=cache_key_for(settings()))
        assert entry.exists
        assert metadata.units_used == "mm"

    def test_opakovany_import_pouzije_cache(self, tmp_path: Path) -> None:
        first = import_step(settings(), tmp_path)
        second = import_step(settings(), tmp_path)

        assert first.to_dict() == second.to_dict()

    def test_the_cache_survives_a_round_trip_to_disk(self, tmp_path: Path) -> None:
        import_step(settings(), tmp_path)

        loaded = CacheEntry(root=tmp_path, key=cache_key_for(settings())).read()

        assert {node.path for node in loaded.assembly.nodes} == {
            "base",
            "base/portal",
            "base/portal/Part1[1]",
            "base/portal/Part1[2]",
            "base/portal/head",
            "base/cover",
        }

    def test_ine_parametre_tesselacie_daju_inu_cache(self, tmp_path: Path) -> None:
        coarse = settings()
        fine = ImportSettings(
            step_file=FIXTURE, scale_to_m=1e-3, units="mm", linear_deflection_mm=0.01
        )

        assert cache_key_for(coarse).digest != cache_key_for(fine).digest

    def test_transformations_survive_serialisation(self, tmp_path: Path) -> None:
        import_step(settings(), tmp_path)

        loaded = CacheEntry(root=tmp_path, key=cache_key_for(settings())).read()
        head = loaded.assembly.node("base/portal/head")

        assert head is not None
        assert head.transform.rpy[2] == pytest.approx(math.pi / 2, abs=1e-9)


class TestBadInput:
    def test_a_missing_file_is_an_error(self, tmp_path: Path) -> None:
        missing = ImportSettings(step_file=tmp_path / "nic.step", scale_to_m=1e-3, units="mm")

        with pytest.raises(CadImportError, match="does not exist"):
            import_step(missing, tmp_path)

    def test_nonsense_content_is_an_error(self, tmp_path: Path) -> None:
        broken = tmp_path / "rozbity.step"
        broken.write_text("toto rozhodne nie je STEP", encoding="utf-8")
        broken_settings = ImportSettings(step_file=broken, scale_to_m=1e-3, units="mm")

        with pytest.raises(CadImportError):
            import_step(broken_settings, tmp_path)
